### ISSUE TITLE
修正电池问题

### ISSUE THREAD

**Issue by xiaoMGitHub** [GlowBlur/Lenovo_G460_Hackintosh#1]
感谢分享EFI，在你的基础上做了些精简，顺便折腾了下电池。

拆分了DSDT中关于电池的几个参数，配合 SMCBatteryManager.kext 驱动电池就能显示，显示数据准不准就有待研究

懒得写热补丁，直接在DSDT上改的
[EFI.zip](https://github.com/GlowBlur/Lenovo_G460_Hackintosh/files/6135012/EFI.zip)

[DSDT.aml.zip](https://github.com/GlowBlur/Lenovo_G460_Hackintosh/files/6135006/DSDT.aml.zip)

**Comment by hackerhui** [comment]
感谢回复，这台十年老机器都快寿终正寝了，闲暇之余还有人有心研究电池驱动，万分感动。
